# 集約ポート（このポートで待ち受けます）
router_port = 3015

# ルーティング先のポート設定
[[targets]]
name = "フロントエンド開発サーバー"
port = 3000
description = "Reactアプリケーション"

[[targets]]
name = "バックエンドAPI"
port = 3001
description = "Express API サーバー"

[[targets]]
name = "データベース管理画面"
port = 3002
description = "PostgreSQL Admin"

[[targets]]
name = "Storybook"
port = 6006
description = "コンポーネントカタログ"